package alrosa.staa.gatekeeper.objects;

public enum Direction {
    MAINSYSTEM, BUREAU, COMPUTER, PERCO, SERVER, PERCOC01, CARDREADER,
    USERS, ADMINS, OPERATORS, GLOBAL_ACCESS_LEVELS, CARDS,
    MAN, WOMAN, GLOBAL_ACCESS_LEVEL, CARD;
}
